<template>
<v-tabs dark v-model="active" :scrollable="false" style="height:100%">
    <v-tabs-bar class="cyan">
        <v-tabs-slider class="yellow"></v-tabs-slider>
        <v-tabs-item
            v-for="item in items"
            :key="item.key"
            :href="item.href"
            class="menu_title"
        >
            {{ item.title }}
        </v-tabs-item>
    </v-tabs-bar>
    <v-tabs-items style="height:100%;">
        <v-tabs-content
            v-for="item in items"
            :key="item.key"
            :id="item.id"
            style="height:100%;transition:0s;"
            :transition="false"
        >
            <div style="height:100%;overflow-y:auto">
                <div style="display:flex;flex-direction:row;flex-wrap:wrap;">
                    <template v-for="(icon, index) in icons">
                        <div style="padding:10px;width:190px;text-align:center;">
                            <i class="material-icons" style="font-size:40px;height:40px;width:40px;">{{ icon }}</i>
                            <div>{{ icon }}</div>
                        </div>
                    </template>
                </div>
            </div>
        </v-tabs-content>
    </v-tabs-items>
</v-tabs>
</template>

<script>
export default {
    data () {
        return {
            active: 'tab-news',
            id: "1",
            items: [
                {
                    title: '动态',
                    key: 'news',
                    href: '#tab-news',
                    id: 'tab-news'
                },
                {
                    title: '详情',
                    key: 'profile',
                    href: '#tab-profile',
                    id: 'tab-profile'
                }
            ],
            icons: [
                'account_box',
                'account_circle',
                'assessment',
                'bookmark',
                'bookmark_border',
                'code',
                'copyright',
                'dashboard',
                'delete',
                'delete_forever',
                'dns',
                'done',
                'done_all',
                'donut_large',
                'donut_small',
                'explore',
                'favorite',
                'favorite_border',
                'fingerprint',
                'get_app',
                'grade',
                'group_work',
                'help',
                'help_outline',
                'highlight_off',
                'history',
                'home',
                'info',
                'info_outline',
                'label',
                'label_outline',
                'language',
                'lock',
                'lock_outline',
                'open_with',
                'payment',
                'perm_identity',
                'pets',
                'polymer',
                'print',
                'query_builder',
                'question_answer',
                'reorder',
                'restore',
                'report_problem',
                'room',
                'schedule',
                'search',
                'settings',
                'settings_applications',
                'settings_input_hdmi',
                'settings_input_svideo',
                'shopping_cart',
                'speaker_notes',
                'star_rate',
                'stars',
                'store',
                'subject',
                'supervisor_account',
                'thumb_down',
                'thumb_up',
                'view_agenda',
                'view_array',
                'view_carousel',
                'view_column',
                'view_day',
                'view_headline',
                'view_list',
                'view_module',
                'view_quilt',
                'view_stream',
                'view_week',
                'visibility',
                'visibility_off',
                'watch_later',
                'work',
                'zoom_in',
                'zoom_out',
                'error',
                'error_outline',
                'warning',
                'add_to_queue',
                'remove_from_queue',
                'album',
                'equalizer',
                'fast_forward',
                'fast_rewind',
                'closed_caption',
                'fiber_new',
                'fiber_pin',
                'high_quality',
                'hd',
                'mic',
                'mic_none',
                'mic_off',
                'new_releases',
                'not_interested',
                'pause',
                'pause_circle_filled',
                'pause_circle_outline',
                'play_arrow',
                'play_circle_filled',
                'play_circle_outline',
                'repeat',
                'replay',
                'skip_next',
                'skip_previous',
                'slow_motion_video',
                'sort_by_alpha',
                'stop',
                'surround_sound',
                'video_call',
                'videocam',
                'videocam_off',
                'volume_down',
                'volume_mute',
                'volume_off',
                'volume_up',
                'video_label',
                'web',
                'web_assert',
                'call',
                'call_end',
                'chat',
                'chat_bubble',
                'chat_bubble_outline',
                'comment',
                'message',
                'contact_mail',
                'contact_phone',
                'email',
                'mail_outline',
                'forum',
                'import_contacts',
                'location_on',
                'location_off',
                'present_to_all',
                'rss_feed',
                'textsms',
                'vpn_key',
                'add',
                'add_box',
                'add_circle',
                'add_circle_outline',
                'remove',
                'remove_circle',
                'remove_circle_outline',
                'archive',
                'unarchive',
                'backspace',
                'block',
                'content_cut',
                'create',
                'drafts',
                'flag',
                'font_download',
                'forward',
                'inbox',
                'move_to_inbox',
                'reply',
                'reply_all',
                'report',
                'save',
                'select_all',
                'send',
                'redo',
                'undo',
                'sort',
                'text_format',
                'access_time',
                'airplanemode_active',
                'airplanemode_inactive',
                'data_usage',
                'dvr',
                'gps_fixed',
                'gps_not_fixed',
                'gps_off',
                'location_disabled',
                'location_searching',
                'network_wifi',
                'nfc',
                'storage',
                'widgets',
                'wallpaper',
                'wifi_tethering',
                'attach_file',
                'attach_money',
                'border_color',
                'border_all',
                'border_clear',
                'border_horizontal',
                'border_inner',
                'border_left',
                'border_outer',
                'border_right',
                'border_style',
                'border_top',
                'border_vertical',
                'format_align_center',
                'format_align_justify',
                'format_align_left',
                'format_align_right',
                'format_bold',
                'format_color_text',
                'format_indent_decrease',
                'format_indent_increase',
                'format_italic',
                'format_line_spacing',
                'format_list_bulleted',
                'format_list_numbered',
                'format_paint',
                'format_quote',
                'format_shapes',
                'format_size',
                'format_strikethrough',
                'format_textdirection_l_to_r',
                'format_textdirection_r_to_l',
                'format_underlined',
                'functions',
                'insert_chart',
                'insert_comment',
                'insert_emoticon',
                'insert_link',
                'insert_photo',
                'mode_comment',
                'mode_edit',
                'pie_chart',
                'pie_chart_outline',
                'text_fields',
                'title',
                'attachment',
                'cloud',
                'cloud_circle',
                'cloud_download',
                'cloud_upload',
                'create_new_folder',
                'folder',
                'folder_open',
                'folder_shared',
                'file_download',
                'file_upload',
                'security',
                'keyboard_voice',
                'gamepad',
                'headset',
                'headset_mic',
                'keyboard_arrow_down',
                'keyboard_arrow_left',
                'keyboard_arrow_right',
                'keyboard_arrow_up',
                'adjust',
                'broken_image',
                'camera',
                'camera_alt',
                'center_focus_strong',
                'center_focus_weak',
                'color_lens',
                'colorize',
                'control_point',
                'crop_free',
                'crop_original',
                'details',
                'edit',
                'exposure',
                'iso',
                'filter_tilt_shift',
                'filter_vintage',
                'layers',
                'local_bar',
                'place',
                'navigation',
                'satellite',
                'near_me',
                'my_location',
                'zoom_out_map',
                'apps',
                'arrow_back',
                'arrow_forward',
                'arrow_upward',
                'arrow_downward',
                'arrow_drop_down',
                'arrow_drop_down_circle',
                'arrow_drop_up',
                'cancel',
                'check',
                'close',
                'chevron_left',
                'chevron_right',
                'expand_less',
                'expand_more',
                'first_page',
                'last_page',
                'fullscreen',
                'menu',
                'refresh',
                'sms',
                'sms_failed',
                'wifi',
                'ac_unit',
                'beach_access',
                'casino',
                'group',
                'mood',
                'mood_bad',
                'pages',
                'people',
                'people_outline',
                'person',
                'person_outline',
                'school',
                'public',
                'share',
                'check_box',
                'check_box_outline_blank',
                'indeterminate_check_box',
                'radio_button_checked',
                'radio_button_unchecked',
                'star',
                'star_border',
                'star_half',
            ]
        }
    },
    created () {
        this.fetchData()
    },
    watch: {
        '$route': 'fetchData'
    },
    methods: {
        fetchData () {
            //do ajax request
            this.id = this.$route.query.id
        }
    }
}
</script>

<style lang="css">

</style>
